(function () {
  var isPublic = /\.pages\.dev$/.test(location.hostname);
  var packNav = document.querySelector('.pack-nav');
  if (packNav && !packNav.querySelector('a[href="phase-2-research.html"]')) {
    var phase2Link = document.createElement('a');
    phase2Link.href = 'phase-2-research.html';
    phase2Link.textContent = 'Phase-2 deep research';
    packNav.appendChild(phase2Link);
  }
  var matrixMetric = Array.prototype.find.call(document.querySelectorAll('.pack-metric'), function (metric) {
    var strong = metric.querySelector('strong');
    return strong && /\d[\d,]* \/ 17,000/.test(strong.textContent);
  });
  if (matrixMetric) {
    matrixMetric.querySelector('strong').textContent = '17,000 / 17,000';
    matrixMetric.querySelector('span').textContent = 'observed matrix slots · 100/cell verified · admission gates active';
  }
  var expansionGrid = document.querySelector('#expansion-packets .pack-grid-3');
  if (expansionGrid && !expansionGrid.querySelector('[data-expansion-added]')) {
    var publicCard = Array.prototype.find.call(expansionGrid.querySelectorAll('.pack-card'), function (card) {
      var heading = card.querySelector('h3');
      return heading && heading.textContent.indexOf('Public signals expansion') !== -1;
    });
    if (publicCard) {
      var publicTag = publicCard.querySelector('.pack-tag');
      if (publicTag) publicTag.textContent = 'VERIFIED';
      var publicSummary = publicCard.querySelector('p');
      if (publicSummary) publicSummary.textContent = '416 cited URLs and 1,360 longitudinal signal slots through Wave 11 across Reddit, X, YouTube/workshops, HN/Indie Hackers, newsletters, first-party docs, and empirical sources, with gated/rate-limited limits retained instead of hidden.';
    }
    expansionGrid.insertAdjacentHTML('beforeend', '<article class="pack-card"><span class="pack-tag purple">VERIFIED</span><h3>Standards expansion</h3><p>566 lines covering TUF, Sigstore, SWHID, CycloneDX, AST/codemod, DTCG/WCAG, MCP/A2A, evals, sandboxing, deployment, and rollback.</p><a data-local-source href="../actionmodel-builder-research-2026-08-26/expansion/outputs/standards-expansion.md">Open standards expansion ↗</a></article><article class="pack-card dark"><span class="pack-tag orange">TRANCHE VERIFIED</span><h3>GitHub expansion</h3><p>500 discovery rows and a 17,000-slot ledger are verified. 15,300 observations are now verified through Wave 10 (90 per cell); 1,700 slots remain for the active Wave 11 floor.</p><a data-local-source href="../actionmodel-builder-research-2026-08-26/expansion/outputs/github-expansion-report.md">Open GitHub expansion report ↗</a><a data-local-source href="../actionmodel-builder-research-2026-08-26/expansion/outputs/repo-matrix-observations.jsonl">Open matrix ledger ↗</a></article>');
    expansionGrid.insertAdjacentHTML('beforeend', '<article class="pack-card dark"><span class="pack-tag">COORDINATOR</span><h3>Expansion synthesis</h3><p>Waves 2–10 are floor-verified; Wave 11 is active. The matrix is at 15,300 observed slots (90 per cell), with 1,700 slots still open in the 100-per-cell research target.</p><a data-local-source href="../actionmodel-builder-research-2026-08-26/expansion/outputs/expansion-synthesis.md">Open expansion synthesis ↗</a></article>');
    expansionGrid.insertAdjacentHTML('beforeend', '<article class="pack-card"><span class="pack-tag blue">FLOOR VERIFIED</span><h3>Wave 2 matrix deepening</h3><p>Five research lanes are complete. All 170 industry×dimension cells now have 10 observed slots (1,700 total); 15,300 slots remain in the active 100-per-cell target.</p><a data-local-source href="../actionmodel-builder-research-2026-08-26/expansion/wave-2/WAVE-2-PROGRAM.md">Open wave-2 program ↗</a><a data-local-source href="../actionmodel-builder-research-2026-08-26/expansion/wave-2/wave-2-state.json">Open wave-2 state ↗</a></article>');
    expansionGrid.insertAdjacentHTML('beforeend', '<article class="pack-card"><span class="pack-tag purple">WAVE 2 PACKS</span><h3>Five finished research lanes</h3><p>Read the full company, public-signal, standards, niche-matrix, and GitHub evidence packs individually. Each keeps its gaps, falsifiers, and research-only boundary visible.</p><a data-local-source href="../actionmodel-builder-research-2026-08-26/expansion/wave-2/outputs/company-dossiers-wave-2.md">Company dossiers ↗</a><a data-local-source href="../actionmodel-builder-research-2026-08-26/expansion/wave-2/outputs/public-signals-wave-2.md">Public signals ↗</a><a data-local-source href="../actionmodel-builder-research-2026-08-26/expansion/wave-2/outputs/standards-applicability-wave-2.md">Standards applicability ↗</a><a data-local-source href="../actionmodel-builder-research-2026-08-26/expansion/wave-2/outputs/niche-matrix-join-wave-2.md">Niche matrix join ↗</a><a data-local-source href="../actionmodel-builder-research-2026-08-26/expansion/wave-2/outputs/github-wave-2-report.md">GitHub wave-2 report ↗</a></article>');
    expansionGrid.insertAdjacentHTML('beforeend', '<article class="pack-card dark"><span class="pack-tag blue">FLOOR VERIFIED</span><h3>Wave 3: 20-per-cell floor</h3><p>All five Luna lanes are complete and independently smoke-verified. The matrix now has 3,400 observations (20 in every one of 170 cells); 13,600 slots remain in the active 100-per-cell target.</p><a data-local-source href="../actionmodel-builder-research-2026-08-26/expansion/wave-3/WAVE-3-PROGRAM.md">Wave-3 program ↗</a><a data-local-source href="../actionmodel-builder-research-2026-08-26/expansion/wave-3/wave-3-state.json">Wave-3 state ↗</a><a data-local-source href="../actionmodel-builder-research-2026-08-26/expansion/wave-3/outputs/company-dossiers-wave-3.md">Company dossiers ↗</a><a data-local-source href="../actionmodel-builder-research-2026-08-26/expansion/wave-3/outputs/public-signals-wave-3.md">Public signals ↗</a><a data-local-source href="../actionmodel-builder-research-2026-08-26/expansion/wave-3/outputs/standards-applicability-wave-3.md">Standards applicability ↗</a><a data-local-source href="../actionmodel-builder-research-2026-08-26/expansion/wave-3/outputs/niche-matrix-join-wave-3.md">Niche matrix join ↗</a><a data-local-source href="../actionmodel-builder-research-2026-08-26/expansion/wave-3/outputs/github-wave-3-report.md">GitHub report ↗</a></article>');
    expansionGrid.insertAdjacentHTML('beforeend', '<article class="pack-card"><span class="pack-tag blue">FLOOR VERIFIED</span><h3>Wave 4: 30-per-cell floor</h3><p>All five persistent lanes are complete and independently verified. The matrix reached 5,100 observations (30 in every one of 170 cells); 11,900 parent slots remained before Wave 5. No implementation or admission is authorized.</p><a data-local-source href="../actionmodel-builder-research-2026-08-26/expansion/wave-4/WAVE-4-PROGRAM.md">Open wave-4 program ↗</a><a data-local-source href="../actionmodel-builder-research-2026-08-26/expansion/wave-4/wave-4-state.json">Open wave-4 state ↗</a><a data-local-source href="../actionmodel-builder-research-2026-08-26/expansion/wave-4/outputs/niche-matrix-join-wave-4.md">Open wave-4 join ↗</a></article>');
    expansionGrid.insertAdjacentHTML('beforeend', '<article class="pack-card dark"><span class="pack-tag blue">FLOOR VERIFIED</span><h3>Wave 5: 40-per-cell floor</h3><p>All five W5 evidence lanes are complete. Indices 31–40 added 1,700 repository observations plus company, public, standards, and niche receipts; every cell is now at 40 (6,800 total), with 10,200 parent slots still open.</p><a data-local-source href="../actionmodel-builder-research-2026-08-26/expansion/wave-5/WAVE-5-PROGRAM.md">W5 program ↗</a><a data-local-source href="../actionmodel-builder-research-2026-08-26/expansion/wave-5/wave-5-state.json">W5 state ↗</a><a data-local-source href="../actionmodel-builder-research-2026-08-26/expansion/wave-5/outputs/company-dossiers-wave-5.md">W5 company dossiers ↗</a><a data-local-source href="../actionmodel-builder-research-2026-08-26/expansion/wave-5/outputs/public-signals-wave-5.md">W5 public signals ↗</a><a data-local-source href="../actionmodel-builder-research-2026-08-26/expansion/wave-5/outputs/standards-applicability-wave-5.md">W5 standards ↗</a><a data-local-source href="../actionmodel-builder-research-2026-08-26/expansion/wave-5/outputs/niche-matrix-join-wave-5.md">W5 niche join ↗</a><a data-local-source href="../actionmodel-builder-research-2026-08-26/expansion/wave-5/outputs/github-wave-5-report.md">W5 GitHub report ↗</a></article>');
    expansionGrid.insertAdjacentHTML('beforeend', '<article class="pack-card dark"><span class="pack-tag blue">FLOOR VERIFIED</span><h3>Wave 6: 50-per-cell floor</h3><p>All five W6 evidence lanes are complete. Indices 41–50 added 1,700 repository observations plus company, public, standards, and niche receipts; every industry×dimension cell is now at 50 (8,500 total), with 8,500 parent slots still open.</p><a data-local-source href="../actionmodel-builder-research-2026-08-26/expansion/wave-6/WAVE-6-PROGRAM.md">W6 program ↗</a><a data-local-source href="../actionmodel-builder-research-2026-08-26/expansion/wave-6/wave-6-state.json">W6 state ↗</a></article>');
    expansionGrid.insertAdjacentHTML('beforeend', '<article class="pack-card dark"><span class="pack-tag blue">FLOOR VERIFIED</span><h3>Wave 7: 60-per-cell floor</h3><p>All five W7 evidence lanes are complete. Indices 51–60 added 1,700 repository observations plus company, public, standards, and niche receipts; every industry×dimension cell is now at 60 (10,200 total), with 6,800 parent slots still open.</p><a data-local-source href="../actionmodel-builder-research-2026-08-26/expansion/wave-7/WAVE-7-PROGRAM.md">W7 program ↗</a><a data-local-source href="../actionmodel-builder-research-2026-08-26/expansion/wave-7/wave-7-state.json">W7 state ↗</a><a data-local-source href="../actionmodel-builder-research-2026-08-26/expansion/wave-7/outputs/company-dossiers-wave-7.md">W7 company ↗</a><a data-local-source href="../actionmodel-builder-research-2026-08-26/expansion/wave-7/outputs/public-signals-wave-7.md">W7 public ↗</a><a data-local-source href="../actionmodel-builder-research-2026-08-26/expansion/wave-7/outputs/standards-applicability-wave-7.md">W7 standards ↗</a><a data-local-source href="../actionmodel-builder-research-2026-08-26/expansion/wave-7/outputs/niche-matrix-join-wave-7.md">W7 niche ↗</a><a data-local-source href="../actionmodel-builder-research-2026-08-26/expansion/wave-7/outputs/github-wave-7-report.md">W7 GitHub ↗</a></article>');
    expansionGrid.insertAdjacentHTML('beforeend', '<article class="pack-card dark"><span class="pack-tag blue">FLOOR VERIFIED</span><h3>Wave 8: 70-per-cell floor</h3><p>All five W8 evidence lanes are complete. Indices 61–70 added 1,700 repository observations plus company, public, standards, and niche receipts; every industry×dimension cell is now at 70 (11,900 total), with 5,100 parent slots still open.</p><a data-local-source href="../actionmodel-builder-research-2026-08-26/expansion/wave-8/WAVE-8-PROGRAM.md">W8 program ↗</a><a data-local-source href="../actionmodel-builder-research-2026-08-26/expansion/wave-8/wave-8-state.json">W8 state ↗</a><a data-local-source href="../actionmodel-builder-research-2026-08-26/expansion/wave-8/outputs/company-dossiers-wave-8.md">W8 company ↗</a><a data-local-source href="../actionmodel-builder-research-2026-08-26/expansion/wave-8/outputs/public-signals-wave-8.md">W8 public ↗</a><a data-local-source href="../actionmodel-builder-research-2026-08-26/expansion/wave-8/outputs/standards-applicability-wave-8.md">W8 standards ↗</a><a data-local-source href="../actionmodel-builder-research-2026-08-26/expansion/wave-8/outputs/niche-matrix-join-wave-8.md">W8 niche ↗</a><a data-local-source href="../actionmodel-builder-research-2026-08-26/expansion/wave-8/outputs/github-wave-8-report.md">W8 GitHub ↗</a></article>');
    expansionGrid.insertAdjacentHTML('beforeend', '<article class="pack-card dark"><span class="pack-tag blue">FLOOR VERIFIED</span><h3>Wave 9: 80-per-cell floor</h3><p>All five W9 evidence lanes are complete and independently verified. Indices 71–80 added 1,700 repository observations plus company, public, standards, and niche receipts; every industry×dimension cell is now at 80 (13,600 total), with 3,400 parent slots still open.</p><a data-local-source href="../actionmodel-builder-research-2026-08-26/expansion/wave-9/WAVE-9-PROGRAM.md">W9 program ↗</a><a data-local-source href="../actionmodel-builder-research-2026-08-26/expansion/wave-9/wave-9-state.json">W9 state ↗</a><a data-local-source href="../actionmodel-builder-research-2026-08-26/expansion/wave-9/outputs/company-dossiers-wave-9.md">W9 company ↗</a><a data-local-source href="../actionmodel-builder-research-2026-08-26/expansion/wave-9/outputs/public-signals-wave-9.md">W9 public ↗</a><a data-local-source href="../actionmodel-builder-research-2026-08-26/expansion/wave-9/outputs/standards-applicability-wave-9.md">W9 standards ↗</a><a data-local-source href="../actionmodel-builder-research-2026-08-26/expansion/wave-9/outputs/niche-matrix-join-wave-9.md">W9 niche ↗</a><a data-local-source href="../actionmodel-builder-research-2026-08-26/expansion/wave-9/outputs/github-wave-9-report.md">W9 GitHub ↗</a></article>');
    expansionGrid.insertAdjacentHTML('beforeend', '<article class="pack-card dark"><span class="pack-tag blue">FLOOR VERIFIED</span><h3>Wave 10: 90-per-cell floor</h3><p>Five persistent Luna lanes are complete and independently audited. Indices 81–90 added 1,700 repository observations and four evidence refreshes; every industry×dimension cell is now at 90 (15,300 total), with 1,700 parent slots still open.</p><a data-local-source href="../actionmodel-builder-research-2026-08-26/expansion/wave-10/WAVE-10-PROGRAM.md">W10 program ↗</a><a data-local-source href="../actionmodel-builder-research-2026-08-26/expansion/wave-10/wave-10-state.json">W10 state ↗</a><a data-local-source href="../actionmodel-builder-research-2026-08-26/expansion/wave-10/outputs/company-dossiers-wave-10.md">W10 company ↗</a><a data-local-source href="../actionmodel-builder-research-2026-08-26/expansion/wave-10/outputs/public-signals-wave-10.md">W10 public ↗</a><a data-local-source href="../actionmodel-builder-research-2026-08-26/expansion/wave-10/outputs/standards-applicability-wave-10.md">W10 standards ↗</a><a data-local-source href="../actionmodel-builder-research-2026-08-26/expansion/wave-10/outputs/niche-matrix-join-wave-10.md">W10 niche ↗</a><a data-local-source href="../actionmodel-builder-research-2026-08-26/expansion/wave-10/outputs/github-wave-10-report.md">W10 GitHub ↗</a></article>');
    expansionGrid.insertAdjacentHTML('beforeend', '<article class="pack-card dark"><span class="pack-tag orange">LONG RUN ACTIVE</span><h3>Wave 11: 100-per-cell target</h3><p>Five persistent Luna lanes are working on indices 91–100: 1,700 new repository observations, four evidence refreshes, and the final exact-cell join from 90 to 100 (17,000 target). Completing this floor still does not authorize implementation or block admission.</p><a data-local-source href="../actionmodel-builder-research-2026-08-26/expansion/wave-11/WAVE-11-PROGRAM.md">W11 program ↗</a><a data-local-source href="../actionmodel-builder-research-2026-08-26/expansion/wave-11/wave-11-state.json">W11 state ↗</a></article>');
    var githubExpansionCard = Array.prototype.find.call(expansionGrid.querySelectorAll('.pack-card'), function (card) {
      var heading = card.querySelector('h3');
      return heading && heading.textContent === 'GitHub expansion';
    });
    if (githubExpansionCard) {
      var githubSummary = githubExpansionCard.querySelector('p');
      if (githubSummary) githubSummary.textContent = '500 discovery rows and a 17,000-slot ledger are verified. All 17,000 observations are now verified through Wave 11 (100 per cell); the numeric matrix floor is complete while admission gates remain open.';
    }
    var synthesisCard = Array.prototype.find.call(expansionGrid.querySelectorAll('.pack-card'), function (card) {
      var heading = card.querySelector('h3');
      return heading && heading.textContent === 'Expansion synthesis';
    });
    if (synthesisCard) {
      var synthesisSummary = synthesisCard.querySelector('p');
      if (synthesisSummary) synthesisSummary.textContent = 'Waves 2–11 are floor-verified. The matrix is at 17,000 observed slots (100 per cell); the remaining work is platform depth, local-corpus discovery, executable evidence, and admission gates.';
    }
    var wave11Card = Array.prototype.find.call(expansionGrid.querySelectorAll('.pack-card'), function (card) {
      var heading = card.querySelector('h3');
      return heading && heading.textContent.indexOf('Wave 11:') === 0;
    });
    if (wave11Card) {
      var wave11Tag = wave11Card.querySelector('.pack-tag');
      if (wave11Tag) {
        wave11Tag.textContent = 'FLOOR VERIFIED';
        wave11Tag.className = 'pack-tag blue';
      }
      var wave11Summary = wave11Card.querySelector('p');
      if (wave11Summary) wave11Summary.textContent = 'Five persistent Luna lanes are complete and independently audited. Indices 91–100 added 1,700 repository observations and four evidence refreshes; every industry×dimension cell is now at 100 (17,000 total). Completing this floor still does not authorize implementation or block admission.';
    }
    expansionGrid.insertAdjacentHTML('beforeend', '<article class="pack-card"><span class="pack-tag purple">NEXT GATE</span><h3>Requirement comparison &amp; admission gates</h3><p>The 100-per-cell numeric floor is complete. The next phase compares the original brief against evidence and runs canonical-contract, rights/SBOM, eval, security, runtime, economics, and client-approval gates.</p><a data-local-source href="../actionmodel-builder-research-2026-08-26/expansion/outputs/requirement-comparison.md">Open requirement comparison ↗</a></article>');
    expansionGrid.lastElementChild.insertAdjacentHTML('beforeend', '<a data-local-source href="../actionmodel-builder-research-2026-08-26/phase-2/PHASE-2-PROGRAM.md">Phase-2 program ↗</a><a data-local-source href="../actionmodel-builder-research-2026-08-26/phase-2/phase-2-state.json">Phase-2 state ↗</a>');
    expansionGrid.lastElementChild.setAttribute('data-expansion-added', 'true');
  }
  var sourceButtons = document.querySelector('.source-buttons');
  if (sourceButtons && !sourceButtons.querySelector('[data-expansion-buttons-added]')) {
    sourceButtons.insertAdjacentHTML('beforeend', '<button data-load-source="../actionmodel-builder-research-2026-08-26/expansion/outputs/standards-expansion.md" data-target="run-reader">standards expansion</button><button data-load-source="../actionmodel-builder-research-2026-08-26/expansion/outputs/github-expansion-report.md" data-target="run-reader">GitHub expansion</button><button data-load-source="../actionmodel-builder-research-2026-08-26/expansion/outputs/repo-matrix-observations.jsonl" data-target="run-reader">matrix ledger</button>');
    sourceButtons.insertAdjacentHTML('beforeend', '<button data-load-source="../actionmodel-builder-research-2026-08-26/expansion/outputs/expansion-synthesis.md" data-target="run-reader">expansion synthesis</button>');
    sourceButtons.insertAdjacentHTML('beforeend', '<button data-load-source="../actionmodel-builder-research-2026-08-26/expansion/outputs/requirement-comparison.md" data-target="run-reader">requirement comparison</button>');
    sourceButtons.insertAdjacentHTML('beforeend', '<button data-load-source="../actionmodel-builder-research-2026-08-26/expansion/wave-2/WAVE-2-PROGRAM.md" data-target="run-reader">wave-2 program</button><button data-load-source="../actionmodel-builder-research-2026-08-26/expansion/wave-2/wave-2-state.json" data-target="run-reader">wave-2 state</button><button data-load-source="../actionmodel-builder-research-2026-08-26/expansion/wave-2/outputs/company-dossiers-wave-2.md" data-target="run-reader">company dossiers</button><button data-load-source="../actionmodel-builder-research-2026-08-26/expansion/wave-2/outputs/public-signals-wave-2.md" data-target="run-reader">public signals</button><button data-load-source="../actionmodel-builder-research-2026-08-26/expansion/wave-2/outputs/standards-applicability-wave-2.md" data-target="run-reader">standards applicability</button><button data-load-source="../actionmodel-builder-research-2026-08-26/expansion/wave-2/outputs/niche-matrix-join-wave-2.md" data-target="run-reader">niche matrix join</button><button data-load-source="../actionmodel-builder-research-2026-08-26/expansion/wave-2/outputs/github-wave-2-report.md" data-target="run-reader">GitHub wave-2 report</button>');
    sourceButtons.insertAdjacentHTML('beforeend', '<button data-load-source="../actionmodel-builder-research-2026-08-26/expansion/wave-3/WAVE-3-PROGRAM.md" data-target="run-reader">wave-3 program</button><button data-load-source="../actionmodel-builder-research-2026-08-26/expansion/wave-3/wave-3-state.json" data-target="run-reader">wave-3 state</button><button data-load-source="../actionmodel-builder-research-2026-08-26/expansion/wave-3/outputs/company-dossiers-wave-3.md" data-target="run-reader">wave-3 company dossiers</button><button data-load-source="../actionmodel-builder-research-2026-08-26/expansion/wave-3/outputs/public-signals-wave-3.md" data-target="run-reader">wave-3 public signals</button><button data-load-source="../actionmodel-builder-research-2026-08-26/expansion/wave-3/outputs/standards-applicability-wave-3.md" data-target="run-reader">wave-3 standards</button><button data-load-source="../actionmodel-builder-research-2026-08-26/expansion/wave-3/outputs/niche-matrix-join-wave-3.md" data-target="run-reader">wave-3 niche join</button><button data-load-source="../actionmodel-builder-research-2026-08-26/expansion/wave-3/outputs/github-wave-3-report.md" data-target="run-reader">wave-3 GitHub report</button>');
    sourceButtons.insertAdjacentHTML('beforeend', '<button data-load-source="../actionmodel-builder-research-2026-08-26/expansion/wave-4/WAVE-4-PROGRAM.md" data-target="run-reader">wave-4 program</button><button data-load-source="../actionmodel-builder-research-2026-08-26/expansion/wave-4/wave-4-state.json" data-target="run-reader">wave-4 state</button>');
    sourceButtons.insertAdjacentHTML('beforeend', '<button data-load-source="../actionmodel-builder-research-2026-08-26/expansion/wave-4/outputs/niche-matrix-join-wave-4.md" data-target="run-reader">wave-4 join</button><button data-load-source="../actionmodel-builder-research-2026-08-26/expansion/wave-5/WAVE-5-PROGRAM.md" data-target="run-reader">wave-5 program</button><button data-load-source="../actionmodel-builder-research-2026-08-26/expansion/wave-5/wave-5-state.json" data-target="run-reader">wave-5 state</button><button data-load-source="../actionmodel-builder-research-2026-08-26/expansion/wave-5/outputs/company-dossiers-wave-5.md" data-target="run-reader">wave-5 company</button><button data-load-source="../actionmodel-builder-research-2026-08-26/expansion/wave-5/outputs/public-signals-wave-5.md" data-target="run-reader">wave-5 public</button><button data-load-source="../actionmodel-builder-research-2026-08-26/expansion/wave-5/outputs/standards-applicability-wave-5.md" data-target="run-reader">wave-5 standards</button><button data-load-source="../actionmodel-builder-research-2026-08-26/expansion/wave-5/outputs/niche-matrix-join-wave-5.md" data-target="run-reader">wave-5 niche</button><button data-load-source="../actionmodel-builder-research-2026-08-26/expansion/wave-5/outputs/github-wave-5-report.md" data-target="run-reader">wave-5 GitHub</button><button data-load-source="../actionmodel-builder-research-2026-08-26/expansion/wave-6/WAVE-6-PROGRAM.md" data-target="run-reader">wave-6 program</button><button data-load-source="../actionmodel-builder-research-2026-08-26/expansion/wave-6/wave-6-state.json" data-target="run-reader">wave-6 state</button>');
    sourceButtons.insertAdjacentHTML('beforeend', '<button data-load-source="../actionmodel-builder-research-2026-08-26/expansion/wave-7/WAVE-7-PROGRAM.md" data-target="run-reader">wave-7 program</button><button data-load-source="../actionmodel-builder-research-2026-08-26/expansion/wave-7/wave-7-state.json" data-target="run-reader">wave-7 state</button>');
    sourceButtons.insertAdjacentHTML('beforeend', '<button data-load-source="../actionmodel-builder-research-2026-08-26/expansion/wave-7/outputs/company-dossiers-wave-7.md" data-target="run-reader">wave-7 company</button><button data-load-source="../actionmodel-builder-research-2026-08-26/expansion/wave-7/outputs/public-signals-wave-7.md" data-target="run-reader">wave-7 public</button><button data-load-source="../actionmodel-builder-research-2026-08-26/expansion/wave-7/outputs/standards-applicability-wave-7.md" data-target="run-reader">wave-7 standards</button><button data-load-source="../actionmodel-builder-research-2026-08-26/expansion/wave-7/outputs/niche-matrix-join-wave-7.md" data-target="run-reader">wave-7 niche</button><button data-load-source="../actionmodel-builder-research-2026-08-26/expansion/wave-7/outputs/github-wave-7-report.md" data-target="run-reader">wave-7 GitHub</button>');
    sourceButtons.insertAdjacentHTML('beforeend', '<button data-load-source="../actionmodel-builder-research-2026-08-26/expansion/wave-8/WAVE-8-PROGRAM.md" data-target="run-reader">wave-8 program</button><button data-load-source="../actionmodel-builder-research-2026-08-26/expansion/wave-8/wave-8-state.json" data-target="run-reader">wave-8 state</button>');
    sourceButtons.insertAdjacentHTML('beforeend', '<button data-load-source="../actionmodel-builder-research-2026-08-26/expansion/wave-8/outputs/company-dossiers-wave-8.md" data-target="run-reader">wave-8 company</button><button data-load-source="../actionmodel-builder-research-2026-08-26/expansion/wave-8/outputs/public-signals-wave-8.md" data-target="run-reader">wave-8 public</button><button data-load-source="../actionmodel-builder-research-2026-08-26/expansion/wave-8/outputs/standards-applicability-wave-8.md" data-target="run-reader">wave-8 standards</button><button data-load-source="../actionmodel-builder-research-2026-08-26/expansion/wave-8/outputs/niche-matrix-join-wave-8.md" data-target="run-reader">wave-8 niche</button><button data-load-source="../actionmodel-builder-research-2026-08-26/expansion/wave-8/outputs/github-wave-8-report.md" data-target="run-reader">wave-8 GitHub</button>');
    sourceButtons.insertAdjacentHTML('beforeend', '<button data-load-source="../actionmodel-builder-research-2026-08-26/expansion/wave-9/WAVE-9-PROGRAM.md" data-target="run-reader">wave-9 program</button><button data-load-source="../actionmodel-builder-research-2026-08-26/expansion/wave-9/wave-9-state.json" data-target="run-reader">wave-9 state</button><button data-load-source="../actionmodel-builder-research-2026-08-26/expansion/wave-9/outputs/company-dossiers-wave-9.md" data-target="run-reader">wave-9 company</button><button data-load-source="../actionmodel-builder-research-2026-08-26/expansion/wave-9/outputs/public-signals-wave-9.md" data-target="run-reader">wave-9 public</button><button data-load-source="../actionmodel-builder-research-2026-08-26/expansion/wave-9/outputs/standards-applicability-wave-9.md" data-target="run-reader">wave-9 standards</button><button data-load-source="../actionmodel-builder-research-2026-08-26/expansion/wave-9/outputs/niche-matrix-join-wave-9.md" data-target="run-reader">wave-9 niche</button><button data-load-source="../actionmodel-builder-research-2026-08-26/expansion/wave-9/outputs/github-wave-9-report.md" data-target="run-reader">wave-9 GitHub receipt</button>');
    sourceButtons.insertAdjacentHTML('beforeend', '<button data-load-source="../actionmodel-builder-research-2026-08-26/expansion/wave-10/WAVE-10-PROGRAM.md" data-target="run-reader">wave-10 program</button><button data-load-source="../actionmodel-builder-research-2026-08-26/expansion/wave-10/wave-10-state.json" data-target="run-reader">wave-10 state</button><button data-load-source="../actionmodel-builder-research-2026-08-26/expansion/wave-10/outputs/company-dossiers-wave-10.md" data-target="run-reader">wave-10 company</button><button data-load-source="../actionmodel-builder-research-2026-08-26/expansion/wave-10/outputs/public-signals-wave-10.md" data-target="run-reader">wave-10 public</button><button data-load-source="../actionmodel-builder-research-2026-08-26/expansion/wave-10/outputs/standards-applicability-wave-10.md" data-target="run-reader">wave-10 standards</button><button data-load-source="../actionmodel-builder-research-2026-08-26/expansion/wave-10/outputs/niche-matrix-join-wave-10.md" data-target="run-reader">wave-10 niche</button><button data-load-source="../actionmodel-builder-research-2026-08-26/expansion/wave-10/outputs/github-wave-10-report.md" data-target="run-reader">wave-10 GitHub</button>');
    sourceButtons.insertAdjacentHTML('beforeend', '<button data-load-source="../actionmodel-builder-research-2026-08-26/expansion/wave-11/WAVE-11-PROGRAM.md" data-target="run-reader">wave-11 program</button><button data-load-source="../actionmodel-builder-research-2026-08-26/expansion/wave-11/wave-11-state.json" data-target="run-reader">wave-11 state</button>');
    sourceButtons.insertAdjacentHTML('beforeend', '<button data-load-source="../actionmodel-builder-research-2026-08-26/expansion/wave-11/outputs/company-dossiers-wave-11.md" data-target="run-reader">wave-11 company</button><button data-load-source="../actionmodel-builder-research-2026-08-26/expansion/wave-11/outputs/public-signals-wave-11.md" data-target="run-reader">wave-11 public</button><button data-load-source="../actionmodel-builder-research-2026-08-26/expansion/wave-11/outputs/standards-applicability-wave-11.md" data-target="run-reader">wave-11 standards</button><button data-load-source="../actionmodel-builder-research-2026-08-26/expansion/wave-11/outputs/niche-matrix-join-wave-11.md" data-target="run-reader">wave-11 niche</button><button data-load-source="../actionmodel-builder-research-2026-08-26/expansion/wave-11/outputs/github-wave-11-report.md" data-target="run-reader">wave-11 GitHub</button>');
    sourceButtons.insertAdjacentHTML('beforeend', '<button data-load-source="../actionmodel-builder-research-2026-08-26/phase-2/PHASE-2-PROGRAM.md" data-target="run-reader">phase-2 program</button><button data-load-source="../actionmodel-builder-research-2026-08-26/phase-2/phase-2-state.json" data-target="run-reader">phase-2 state</button>');
    sourceButtons.lastElementChild.setAttribute('data-expansion-buttons-added', 'true');
  }
  var localLinks = document.querySelectorAll('[data-local-source]');
  if (isPublic) {
    localLinks.forEach(function (link) {
      link.setAttribute('href', '#source-shelf');
      link.textContent = 'Kept in local pack';
      link.classList.add('local-locked');
      link.setAttribute('aria-label', 'Source kept in local pack');
    });
    document.querySelectorAll('[data-source-reader]').forEach(function (reader) {
      var output = reader.querySelector('pre');
      if (output) output.textContent = 'The raw checkpoint files remain in the local Action Model pack. This public page contains the detailed readout without exposing the private source tree.';
    });
  }

  document.querySelectorAll('[data-load-source]').forEach(function (button) {
    button.addEventListener('click', async function () {
      var target = document.getElementById(button.dataset.target);
      if (!target) return;
      if (isPublic) {
        target.textContent = 'Raw source retained locally; the public resource room shows the full interpreted readout above.';
        return;
      }
      target.textContent = 'Loading ' + button.dataset.loadSource + '…';
      try {
        var response = await fetch(button.dataset.loadSource);
        if (!response.ok) throw new Error('HTTP ' + response.status);
        var text = await response.text();
        if (/\.json$/i.test(button.dataset.loadSource)) {
          try { text = JSON.stringify(JSON.parse(text), null, 2); } catch (error) { /* preserve raw JSON */ }
        }
        target.textContent = text;
      } catch (error) {
        target.textContent = 'Source reader could not load this file. Open the local path directly: ' + button.dataset.loadSource + '\n\n' + error.message;
      }
    });
  });

  window.__verify = {
    runAll: function () {
      return [
        { id: 'pack-shell', pass: !!document.querySelector('.pack-shell') },
        { id: 'pack-hero', pass: !!document.querySelector('.pack-hero h1') },
        { id: 'detail-sections', pass: document.querySelectorAll('.pack-section').length >= 4 },
        { id: 'evidence-shelf', pass: document.querySelectorAll('[data-local-source]').length >= 3 },
        { id: 'source-reader', pass: !!document.querySelector('[data-source-reader]') }
      ];
    }
  };
}());
